apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: {{ .Values.frontendService.type }}
  ports:
    - port: {{ .Values.frontendService.port }}
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: {{ .Values.mongodbService.type }}
  ports:
    - port: {{ .Values.mongodbService.port }}
  selector:
    app: mongodb
